# Generated by Django 5.2.4 on 2026-07-17 14:56

import core.models
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(
                max_length=1024,
                unique=True,
                upload_to=core.models.File.get_upload_path,
            ),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                models.F('created_by'),
                condition=models.Q(('parent__isnull', True)),
                name='uniq_root_folder_name_ci',
            ),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                models.F('created_by'),
                models.F('parent'),
                condition=models.Q(('parent__isnull', False)),
                name='uniq_child_folder_name_ci',
            ),
        ),
    ]
